apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    app: liveness
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: liveness-service
spec:
  type: NodePort
  selector:
    app: liveness
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
